apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: capstone
    region: us-west-1
    version: '1.17'
iam:
    withOIDC: true
managedNodeGroups:
    - name: udacity-t2micro
      instanceType: t2.micro
      desiredCapacity: 2
      minSize: 1
      maxSize: 3