---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: blue
    labels:
        app: blue
    namespace: default
spec:
    replicas: 2
    selector:
        matchLabels:
            app: blue
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: blue
        spec:
            containers:
                - image: 7akim/capstone-devops
                  imagePullPolicy: Always
                  name: blue
                  ports:
                      - containerPort: 80
                        protocol: TCP
                  resources:
                      limits:
                          cpu: "0.5"
                          memory: 200Mi
                      requests:
                          cpu: "0.2"
apiVersion: v1
kind: Service
metadata:
    name: capstone-service
spec:
    selector:
        app: blue
    type: LoadBalancer
    ports:
        - protocol: TCP
          targetPort: 80
          port: 80